# Auto-generated by .github/workflows/homebrew-tap.yml — do not hand-edit.
# Source template: packages/homebrew-tap/pythinker-code.rb.tmpl
class PythinkerCode < Formula
  desc "Terminal-native review-first AI engineering agent"
  homepage "https://pythinker.com"
  version "0.23.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.23.0/pythinker-0.23.0-aarch64-apple-darwin.tar.gz"
      sha256 "fa9b2ca10f42918c9c20fb96f4a04ea42ebd056d5f9916eaba415fc6c560a4b0"
    end

    on_intel do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.23.0/pythinker-0.23.0-x86_64-apple-darwin.tar.gz"
      sha256 "8fbb226348d86162a89e776737b1f0e6def995717d53bfbeb75633fbe84c0c7f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.23.0/pythinker-0.23.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6fd70696a932f2567e1726feb33f20d45eb9aad287eadc6bd6fcc42d3b03a921"
    end

    on_intel do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.23.0/pythinker-0.23.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "58a45731e0bf5e47b79414ebfeb8668e05c2cf2a9a63dfd094c77b5e92bba7a2"
    end
  end

  def install
    libexec.install "pythinker"
    (libexec/".pythinker-native").write "pythinker-native-build\n"
    bin.write_exec_script libexec/"pythinker"
  end

  test do
    assert_path_exists libexec/".pythinker-native"
    assert_match version.to_s, shell_output("#{bin}/pythinker --version")
  end
end
