# Auto-generated by .github/workflows/homebrew-tap.yml — do not hand-edit.
# Source template: packages/homebrew-tap/pythinker-code.rb.tmpl
class PythinkerCode < Formula
  desc "Terminal-native review-first AI engineering agent"
  homepage "https://pythinker.com"
  version "0.34.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.34.0/pythinker-0.34.0-aarch64-apple-darwin-onedir.tar.gz"
      sha256 "82b2eeb8b2de1a9396b9d021427c79da7a8bc240303c06f8f68923224d6397e7"
    end

    on_intel do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.34.0/pythinker-0.34.0-x86_64-apple-darwin-onedir.tar.gz"
      sha256 "d5a6e56d561dcc7a05f24641bb7491be40ca6b28449b1630139a30cd28405ab0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.34.0/pythinker-0.34.0-aarch64-unknown-linux-gnu-onedir.tar.gz"
      sha256 "7676f6e9c70975f8aed041385dfbcd37bde69ff88b6391005379e854fdb6e40a"
    end

    on_intel do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.34.0/pythinker-0.34.0-x86_64-unknown-linux-gnu-onedir.tar.gz"
      sha256 "1968f43081241bf365cc408df2646cb7d910afc91d2bad215fa84025ec14828b"
    end
  end

  def install
    # Onedir PyInstaller build: a "pythinker" launcher next to an "_internal"
    # directory. Homebrew chdirs into the tarball's single "pythinker/" root,
    # so Dir["*"] is the launcher plus _internal. Install the whole tree into
    # libexec and put an exec wrapper on PATH so the launcher resolves
    # _internal next to its real location.
    libexec.install Dir["*"]
    (libexec/".pythinker-native").write "pythinker-native-build\n"
    bin.write_exec_script libexec/"pythinker"
  end

  def caveats
    # Static settled frame of the curl/PowerShell installers' "Tetris" logo
    # (install.sh / install.ps1). Homebrew renders caveats as plain text, so
    # this is the uncoloured robot-head. The squiggly heredoc strips the common
    # leading indent, so the art sits one column left of the curl banner.
    <<~EOS

            ●
            │
        ▛▀▀▀▀▀▀▀▜
       ◖█ ◉   ◉ █◗
        ▙▄▄▄≡▄▄▄▟

        pythinker code · your next CLI agent
    EOS
  end

  test do
    assert_path_exists libexec/".pythinker-native"
    assert_match version.to_s, shell_output("#{bin}/pythinker --version")
  end
end
