# Auto-generated by .github/workflows/homebrew-tap.yml — do not hand-edit.
# Source template: packages/homebrew-tap/pythinker-code.rb.tmpl
class PythinkerCode < Formula
  desc "Terminal-native review-first AI engineering agent"
  homepage "https://pythinker.com"
  version "0.49.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.49.0/pythinker-0.49.0-aarch64-apple-darwin-onedir.tar.gz"
      sha256 "1f6a62016808e2f6a79ace27b2f606e16a14e79206ac1680cdbc6008cecedcf5"
    end

    on_intel do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.49.0/pythinker-0.49.0-x86_64-apple-darwin-onedir.tar.gz"
      sha256 "35eab2a7f3bb92159bd552c25407e341f7449c387751fd69fe4b1a829b9fe32d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.49.0/pythinker-0.49.0-aarch64-unknown-linux-gnu-onedir.tar.gz"
      sha256 "b3058bb9b0b148ff7c1e48b8aced64db6d520e4be36fc02a8f5705c7385f15d4"
    end

    on_intel do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.49.0/pythinker-0.49.0-x86_64-unknown-linux-gnu-onedir.tar.gz"
      sha256 "5082dbe2c5376ac22ca3c37f788c7e73b7d2661bdd01daa936a51546acd409d4"
    end
  end

  def install
    # Onedir PyInstaller build: a "pythinker" launcher next to an "_internal"
    # directory. Homebrew chdirs into the tarball's single "pythinker/" root,
    # so Dir["*"] is the launcher plus _internal. Install the whole tree into
    # libexec and put an exec wrapper on PATH so the launcher resolves
    # _internal next to its real location.
    libexec.install Dir["*"]
    (libexec/".pythinker-native").write "pythinker-native-build\n"
    bin.write_exec_script libexec/"pythinker"
  end

  def caveats
    # Static settled frame of the curl/PowerShell installers' "Tetris" logo
    # (install.sh / install.ps1). Homebrew renders caveats as plain text, so
    # this is the uncoloured robot-head. The squiggly heredoc strips the common
    # leading indent, so the art sits one column left of the curl banner.
    <<~EOS

            ●
            │
        ▛▀▀▀▀▀▀▀▜
       ◖█ ◉   ◉ █◗
        ▙▄▄▄≡▄▄▄▟

        pythinker code · your next CLI agent
    EOS
  end

  test do
    assert_path_exists libexec/".pythinker-native"
    assert_match version.to_s, shell_output("#{bin}/pythinker --version")
  end
end
